version: "3"

services:
  wsgi:
    build: .
    volumes:
      - .:/code
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 8000
    links:
      - redis:redis
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --timeout 240
    depends_on:
      - redis
      - db
    working_dir: /code/project
  asgi:
    build: .
    volumes:
      - .:/code
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9000
    links:
      - redis:redis
    command: daphne -b 0.0.0.0 -p 9000 project.asgi:application
    depends_on:
      - redis
      - db
    working_dir: /code/project
  celery:
    build: .
    volumes:
      - .:/code
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - redis:redis
    command: celery -A project worker -l INFO
    depends_on:
      - wsgi
      - asgi
      - redis
      - db
    working_dir: /code/project
  redis:
    image: redis
    expose:
      - 6379
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  caddy:
    image: caddy
    restart: unless-stopped
    depends_on:
      - wsgi
      - asgi
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: