# Generated by Django 3.1.6 on 2021-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
