from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('enroll/', views.enroll_view, name='enroll'),
    path('unenroll/<slug:class_pk>/', views.unenroll_view, name='unenroll'),
    path('class/<slug:class_pk>/', views.class_view, name='class'),
    path('grades/<slug:class_pk>/', views.grades_view, name='grades'),
    path('download_grades/<slug:class_pk>/<slug:assignment_pk>/', views.download_grades_view, name='download_grades'),
    path('class_assignments_update/<slug:pk>/', views.ClassAssignmentsUpdateView.as_view(), name='class_assignments_update'),
    path('assignment/create/', views.AssignmentCreateView.as_view(), name='assignment_create'),
    path('assignment/update/<slug:pk>/', views.AssignmentUpdateView.as_view(), name='assignment_update'),
    path('assignment/delete/<slug:pk>/', views.AssignmentDeleteView.as_view(), name='assignment_delete'),
    path('fixture/create/', views.FixtureCreateView.as_view(), name='fixture_create'),
    path('fixture/update/<slug:pk>/', views.FixtureUpdateView.as_view(), name='fixture_update'),
    path('fixture/delete/<slug:pk>/', views.FixtureDeleteView.as_view(), name='fixture_delete'),
    path('file/create/', views.FileCreateView.as_view(), name='file_create'),
    path('file/update/<slug:pk>/', views.FileUpdateView.as_view(), name='file_update'),
    path('file/delete/<slug:pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('level/create/', views.LevelCreateView.as_view(), name='level_create'),
    path('level/update/<slug:pk>/', views.LevelUpdateView.as_view(), name='level_update'),
    path('level/delete/<slug:pk>/', views.LevelDeleteView.as_view(), name='level_delete'),
    path('step/select/', views.StepSelectView.as_view(), name='step_select'),
    path('step/update/<slug:pk>/', views.StepUpdateView.as_view(), name='step_update'),
    path('run_step/create/', views.RunStepCreateView.as_view(), name='run_step_create'),
    path('run_step/update/<slug:pk>/', views.RunStepUpdateView.as_view(), name='run_step_update'),
    path('run_step/delete/<slug:pk>/', views.RunStepDeleteView.as_view(), name='run_step_delete'),
    path('test_step/create/', views.TestStepCreateView.as_view(), name='test_step_create'),
    path('test_step/update/<slug:pk>/', views.TestStepUpdateView.as_view(), name='test_step_update'),
    path('test_step/delete/<slug:pk>/', views.TestStepDeleteView.as_view(), name='test_step_delete'),
    path('file_schema/create/', views.FileSchemaCreateView.as_view(), name='file_schema_create'),
    path('file_schema/update/<slug:pk>/', views.FileSchemaUpdateView.as_view(), name='file_schema_update'),
    path('file_schema/delete/<slug:pk>/', views.FileSchemaDeleteView.as_view(), name='file_schema_delete'),
    path('text/create/', views.TextCreateView.as_view(), name='text_create'),
    path('text/update/<slug:pk>/', views.TextUpdateView.as_view(), name='text_update'),
    path('text/delete/<slug:pk>/', views.TextDeleteView.as_view(), name='text_delete'),
    path('submit/<slug:class_pk>/<slug:assignment_pk>/', views.submit_view, name='submit'),
    path('submission/<slug:submission_pk>/', views.submission_view, name='submission'),
    path('run_submission/<slug:submission_pk>/', views.run_submission_view, name='run_submission'),
    path('run_assignment/<slug:class_pk>/<slug:assignment_pk>/', views.run_assignment_view, name='run_assignment'),
    path('plagiarism/<slug:class_pk>/<slug:assignment_pk>/', views.plagiarism_view, name='plagiarism'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='password_reset/request.html', subject_template_name='password_reset/subject.txt', html_email_template_name='password_reset/email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset/done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/complete.html'), name='password_reset_complete'),
    path('', views.index_view, name='index'),
]